# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25b463af69fe3132f054d61090c7b3a51146512bbaac010e7dedcf35f69ae255cf2917ab874cc4a89eca976797ecc6d55cddca4e7da357523bfc3f8be77b2bb

test:
  secret_key_base: 12d682c70f9a41660c04e2389d44a1b9edb59a372a1c90b883112277cb4eaea40c0786cba41b35bd2668991e74b21ef5f3b540af08e3384c033f8d9bde9be45c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
